import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/shared/styles/global.css';

export const metadata: Metadata = {
    title: 'Развитие IT',
    description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['cyrillic', 'latin'] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${inter.className} antialiased`}>{children}</body>
        </html>
    );
}
